fix: close unclosed {% if user %} in all 3 nav sections of base.html
  Redundant nested {% if user.tag == 'admin' %} blocks in desktop/sidebar/drawer
  navs were consuming the endif that closed {% if user %}, causing:
  jinja2.exceptions.TemplateSyntaxError: Unexpected end of template